[package]
name = "honeycomb"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
speedy2d = "1.12.0"
rand = "0.8.5"

[[example]]
name = "grid_demo"
path = "examples/grid_demo.rs"

[[example]]
name = "custom_data"
path = "examples/custom_data.rs"